config/routes.rb
Rails.application.routes.draw do
 
 devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  namespace :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    resources :customers, only: [:edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'cart_items_destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        get :complete
        get :comfirm
        post :comfirm
      end
      member do
      end
    end
    #get 'orders/complete'
    #post 'orders/comfirm'
    #get 'orders/comfirm'
  end

  namespace :admin do
    root to: 'homes#top'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :items, through: :cart_items
         
  def full_name
    self.last_name + self.first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def add_tax_price
    (price*1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {waiting: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, shipped: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { cannot: 0, waiting_for_production: 1, production: 2, production_completed:3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).per(10)
  end
  
private
  
  def order_params
    params.require(:order).permit(:customer_id, :status)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save!
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @shipping_cost = 800
    @order.order_details
  end
  
  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      @order.order_details.update_all(making_status: "waiting_for_production") if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order)
   
  end
  
  private
  
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :total_payment, :payment_method, :shipping_cost, :status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
      admin_root_path
  end
  
  def after_sign_out_path_for(resource)
      new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # def after_sign_in_path_for(resource)
  #   case resource
  #   when Customer
  #     public_root_path
  #   when Admin
  #     admin_root_path
  #   end
  # end
  
  # def after_sign_out_path_for(resource)
  #   case resource
  #   when Customer
  #     public_root_path
  #   when Admin
  #     new_admin_session_path
  #   end
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :passward, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :passward])

  end
end

app/helpers/admin/customer_helper.rb
module Admin::CustomerHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class = "container">
  <h3 class = "ml-5 mb-5">ジャンル編集</h3>
  
  <%= form_with model: @genre, url: admin_genre_path(@genre) do |f| %>
  <%= f.label "ジャンル名", class: "mr-5" %>
  <%= f.text_field :name, class: "mr-5" %>
  <%= f.submit '変更を保存', class: "btn btn-success" %>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class = "container">
<h3 class = "ml-5">ジャンル一覧・追加</h3>

<%= form_with model: @genre, url: admin_genres_path ,method: :POST do |f| %>
<div class = "row mb-5">
  <%= f.label "ジャンル名", class: "mr-5" %>
  <%= f.text_field :name, class: "mr-5"%>
  <%= f.submit "新規登録", class: "btn btn-success" %>
</div>
<% end %>
<div class = "row">
<table class = "table col-md-4">
  <thead class = "table-secondary">
    <tr>
      <th><div class = "ml-5">ジャンル</div></th>
    </tr>
  </thead>
  <% @genres.each do |genre| %>
  <tbody>
    <tr>
      <td>
        <%= genre.name %>
        <div class = "text-right">
          <%= link_to '編集する', edit_admin_genre_path(genre.id), class: "btn btn-success" %>
        </div>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>
</div>
</div>

app/views/admin/items/edit.html.erb
<div class = "container">
  
  <h3 class = "ml-5 mb-5">商品編集</h3>
  <%= form_with model: @item, url: admin_item_path(@item.id) do |f| %>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "商品画像" %>
    </div>
    <div class = "col-md-3">
      <%= f.file_field :image, accept: "image/*" %><br />
    </div>
  </div>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "商品名" %>
    </div>
    <%= f.text_field :name, class: "form-control col-md-3" %>
  </div>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "商品説明" %>
    </div>
    <%= f.text_area :introduction, class: "form-control col-md-3" %>
  </div>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "ジャンル" %>
    </div>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, {}, class: "form-control col-md-3" %>
  </div>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "税抜価格" %>
    </div>
    <%= f.text_field :price, class: "form-control col-md-3" %>円
  </div>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "販売ステータス" %>
    </div>
    <div class = "col-md-4">
      <%= f.radio_button :is_active, :true, checked: true %>
      <%= f.label :is_active, '販売中' %>
      <%= f.radio_button :is_active, :false %>
      <%= f.label :is_active, '販売停止中' %>
    </div>
  </div>
  <div class = "row">
    <div class = "col-md-6 mx-auto">
    <%= f.submit '変更を保存', class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-8">
        <h3 class = "ml-3 mb-5">商品一覧</h3>
        </div>
        <div class = "col-1">
        <div class = "justify-content-md-end">
            <%= link_to "＋", new_admin_item_path, class: "btn btn-outline-dark rounded-circle p-0", style: "width:2rem;height:2rem;" %>
        </div>
        </div>
    
    </div>
    <div class = "row">
        <div class = "col-10">
            <table class = "table">
                <thead class = "table-secondary">
                    <tr>
                        <th class = "col-md-1">商品ID</th>
                        <th>商品名</th>
                        <th>税抜価格</th>
                        <th>ジャンル</th>
                        <th>ステータス</th>
                    </tr>
                </thead>
                <% @items.each do |item| %>
                <tbody>
                    <tr>
                        <td><%= item.id %></td>
                        <td><%= item.name %></td>
                        <td><%= item.price %></td>
                        <td><%= item.genre.name %></td>
                        <td>
                            <% if item.is_active %>
                            <div class = "text-success">
                                販売中
                            </div>
                            <% else %>
                            <div class = "text-secondary">
                                販売停止中
                            </div>
                            <% end %>
                        </td>
                    </tr>
                </tbody>
                <% end %>
            </table>
        </div>
    </div>
    <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class = "container">
  <div class = "ml-5 mb-5">
    <h3>商品新規登録</h3>
  </div>
  <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "商品画像" %>
    </div>
    <div class = "col-md-3">
      <%= f.file_field :image, accept: "image/*" %><br />
    </div>
  </div>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "商品名" %>
    </div>
    <%= f.text_field :name, class: "form-control col-md-3" %>
  </div>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "商品説明" %>
    </div>
    <%= f.text_area :introduction, class: "form-control col-md-3" %>
  </div>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "ジャンル" %>
    </div>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, { include_blank: '--選択してください--'}, class: "form-control col-md-3" %>
  </div>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "税抜価格" %>
    </div>
    <%= f.text_field :price, class: "form-control col-md-3" %>円
  </div>
  <div class = "row mb-3">
    <div class = "col-md-2">
      <%= f.label "販売ステータス" %>
    </div>
    <div class = "col-md-4">
      <%= f.radio_button :is_active, :true, checked: true %>
      <%= f.label :is_active, '販売中' %>
      <%= f.radio_button :is_active, :false %>
      <%= f.label :is_active, '販売停止中' %>
    </div>
  </div>
  <div class = "row">
    <div class = "col-md-6 mx-auto">
    <%= f.submit '新規登録', class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class = "container">
  <h3 class = "ml-5 mb-5">商品詳細</h3>
  <div class = "row">
    <div class = "col-md-3">
      <% if @item.image.attached? %>
        <%= image_tag @item.image, size: "200x200" %>
      <% else %>
        <%= image_tag 'no_image', size: "200x200" %>
      <% end %>
    </div>
    <div class = "col-md-9">
      <div class = "row mb-3">
        <div class = "col-md-2">
          <label>商品名</label>
        </div>
        <div class = "col-md-5">
          <%= @item.name %>
        </div>
      </div>
      <div class = "row mb-3">
        <div class = "col-md-2">
          <label>商品説明</label>
        </div>
        <div class = "col-md-5">
          <%= @item.introduction %>
        </div>
      </div>
      <div class = "row mb-3">
        <div class = "col-md-2">
          <label>ジャンル</label>
        </div>
        <div class = "col-md-5">
          <%= @item.genre.name %>
        </div>
      </div>
      <div class = "row mb-3">
        <div class = "col-md-2">
          <label>税込価格<br />(税抜価格)</label>
          </div>
        <div class = "col-md-5 d-flex align-items-center">
          <%= @item.add_tax_price %>
          (<%= @item.price %>)円
        </div>
      </div>
      <div class = "row mb-3">
        <div class = "col-md-2">
          <label>販売ステータス</label>
        </div>
        <div class = "col-md-5">
          <% if @item.is_active %>
          <div class = "text-success">
            販売中
          </div>
          <% else %>
          <div class = "text-secondary">
            販売停止中
          </div>
          <% end %>
        </div>
      </div>
      <div class = "row">
         <div class = "col offset-md-1">
          <%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-success col-md-2" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class = "container">
<h3>注文履歴詳細</h3>
<div class = "row mb-2">
  <h5 class = "col-md-2">購入者</h5>
  <%= @order.customer.full_name %>
</div>
<div class = "row mb-2">
  <h5 class = "col-md-2">購入日</h5>
  <%= @order.created_at.strftime('%Y/%m/%d') %>
</div>
<div class = "row mb-2">
  <h5 class = "col-md-2">配送先</h5>
  <%= "〒" + @order.postal_code + " " + @order.address %><br/>
  <%= @order.name %>
</div>
<div class = "row mb-2">
  <h5 class = "col-md-2">支払方法</h5>
  <%= @order.payment_method_i18n %><br/>
</div>
<div class = "row mb-2">
  <h5 class = "col-md-2">注文ステータス</h5>
  <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
  <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
  <%= f.submit "更新", class: "btn btn-success" %>
  <% end %>
  <br/>
</div>
<div class = "row">
  <div class = "col-md-8">
  <table class = "table">
    <thead>
      <tr>
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= order_detail.item.add_tax_price %></td>
        <td><%= order_detail.amount %></td>
        <td><%= order_detail.item.add_tax_price * order_detail.amount %></td>
        <td>
          <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
          <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
          <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  
  </div>
  <div class = "col-md-3 align-self-end">
    <table>
      <tr>
        <th>商品合計</th>
        <td><%= @order.total_payment - @shipping_cost %>円</td>
      </tr>
      <tr>
        <th>送料</th>
        <td><%= @shipping_cost %>円</td>
      </tr>
      <tr>
        <th>請求金額合計</th>
        <td><%= @order.total_payment %>円</td>
      </tr>
    </table>
  </div>
</div>
</div>